services:
  backend:
    build: .
    container_name: mielenosoitukset_fi
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mielenosoitukset
      - HOST=0.0.0.0
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: miekkari_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  mongo_data:
